version: '2'
services:
  geoserver:
    image: piensalabs/geoserver:konten
    ports:
      - "8080:8080"
    environment:
      - DJANGO_URL=http://django:8000/
      - GEOSERVER_PUBLIC_LOCATION=http://geonode/geoserver/
      - GEOSERVER_LOCATION=http://geoserver:8080/geoserver/
      - SITEURL=http://geonode/
  nginx:
    build: .
    ports:
      - "80:80"

